version: '3.6'

services:
  web:
    build:
      dockerfile: Dockerfile.prod
    labels:
      - "traefik.backend=${TRAEFIK_BACKEND}"
      - "traefik.docker.network=prod"
      - "traefik.frontend.rule=Host:${TRAEFIK_URL}"
      - "traefik.enable=true"
    networks:
      - default
      - prod

networks:
  prod:
    external: true
    name: ${TRAEFIK_NETWORK}

